x-constants:
  backend_host: &backend_host localhost
  backend_port: &backend_port 5000
  db_host: &db_host db
  db_port: &db_port 3306
  db_name: &db_name geocontrol_db
  db_user: &db_user geocontrol_user
  db_password: &db_password secret

services:
  frontend:
    image: smpolito/geocontrolui:latest
    container_name: geocontrol-frontend
    ports:
      - "5173:5173" 
    volumes: 
      - ./frontend/env-vars.json:/app/dist/config.json 
    depends_on:
      - backend

  backend:
    build:
      context: ../
      dockerfile: docker/backend/Dockerfile
    container_name: geocontrol-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_TYPE: mysql
      DB_HOST: *db_host
      DB_PORT: *db_port
      DB_USERNAME: *db_user
      DB_PASSWORD: *db_password
      DB_NAME: *db_name
      PORT: *backend_port
    ports:
      - "5000:5000"
    volumes:
      - ../src:/app/src
      - ../scripts:/app/scripts
      - ../tsconfig.json:/app/tsconfig.json
      - ../package.json:/app/package.json

  db:
    image: mysql:8.0
    container_name: geocontrol-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: *db_name
      MYSQL_USER: *db_user
      MYSQL_PASSWORD: *db_password
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
volumes:
  db_data:
